sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
addons:
  apt:
    packages:
    - openjdk-7-jre-headless
before_script:
  - npm install -g grunt mocha
script:
  - grunt
